// create layout with sidebar to wrap around different pages
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Sidebar = () => {
  return (
    <div className="sidebar">
      <div className="sidebar-header">
        <h3>Sidebar</h3>
      </div>
      <div className="sidebar-content">
        <ul>
          <li>
            <a href="#">Overview</a>
          </li>
          <li>
            <a href="#">Facebook</a>
          </li>
          <li>
            <a href="#">Twitter</a>
          </li>
        </ul>
      </div>
    </div>
  );
};

// const Layout = ({ children, activePage }) => {
//   return (
//     <>
//       <Sidebar activePage={activePage} />
//       {children}
//     </>
//   );
// };
const Layout = ({ children, activePage }) => {
  return (
    <div className="drawer drawer-mobile">
      <input id="side-drawer" type="checkbox" className="drawer-toggle" />
      <div className="drawer-content flex flex-col items-center justify-center">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <div>
            {/* <!-- Page content here --> */}
            <label
              for="side-drawer"
              className="btn btn-primary drawer-button lg:hidden"
            >
              Open
            </label>
            <div className="flex flex-col items-center justify-center">
              <h1 className="text-3xl font-bold">{activePage.toUpperCase()}</h1>
              <div className="flex flex-col items-center justify-center">
                {children}
              </div>
            </div>
          </div>
          <footer className={styles.footer}>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Powered by{" "}
              <span className={styles.logo}>
                <Image
                  src="/logo_sq.png"
                  alt="Supertype"
                  width={50}
                  height={50}
                />
              </span>
            </a>
          </footer>
        </main>
      </div>
      {/* <!-- End of drawer --> */}
      <div className="drawer-side">
        <label for="side-drawer" className="drawer-overlay"></label>
        <ul className="menu p-4 overflow-y-auto w-80 bg-base-100 text-base-content">
          <a href="https://www.bi.go.id">
            <span className={styles.logo}>
              <Image
                src="/bi-b.png"
                alt="Bank Indonesia Logo"
                className="grayscale brightness-200"
                width={220.1}
                height={69.7}
              />
            </span>
          </a>

          <li>
            <Link href="/overview">
              <a>Overview</a>
            </Link>
          </li>
          <li>
            <Link href="/facebook">
              <a>Facebook</a>
            </Link>
          </li>
          <li>
            <Link href="/instagram">
              <a>Instagram</a>
            </Link>
          </li>
          <li>
            <Link href="/twitter">
              <a>Twitter</a>
            </Link>
          </li>
          <li>
            <Link href="/youtube">
              <a>YouTube</a>
            </Link>
          </li>
        </ul>
      </div>
    </div>
  );
};

export default Layout;
