import { useEffect } from 'react';

import Head from 'next/head'
import Router from 'next/router';

import { useLogin } from '../context/UserContext';
import Layout from '../components/Layout';
import styles from '../styles/Home.module.css'

export default function Home() {
  const { user } = useLogin();
  
  useEffect(() => {
    if(!user){
      if(!localStorage.getItem("BIAuthTokens")){
        Router.push("/login");
      }
    }
  }, [user]);

  return (
    <Layout>
      <div className="drawer drawer-mobile">
        <input id="side-drawer" type="checkbox" className="drawer-toggle" />
        <div className="drawer-content flex flex-col items-center justify-center">

          <Head>
            <title>Social Analytics</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main>
            <div>
              <h1 className={styles.title}>
                Social Media Analytics
              </h1>
              <label htmlFor="side-drawer" className="btn btn-primary drawer-button lg:hidden">Open</label>
            </div>
            <footer className={styles.footer}>
              <a
                href="https://supertype.ai"
                target="_blank"
                rel="noopener noreferrer"
              >
                Powered by Supertype
              </a>
            </footer>
          </main>

        </div>
      </div>
    </Layout>
  );
};
