import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="drawer drawer-mobile">
      <input id="side-drawer" type="checkbox" className="drawer-toggle" />
      <div className="drawer-content flex flex-col items-center justify-center">

        <Head>
          <title>Social Analytics</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <div>
            {/* <!-- Page content here --> */}
            <h1 className={styles.title}>
              Welcome to <a href="https://supertype.ai">Supertype</a>
            </h1>
            <label for="side-drawer" className="btn btn-primary drawer-button lg:hidden">Open</label>
          </div>
          <footer className={styles.footer}>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Powered by{' '}
              <span className={styles.logo}>
                <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
              </span>
            </a>
          </footer>
        </main>
      </div>{/* <!-- End of drawer --> */}
      <div className="drawer-side">
        <label for="side-drawer" className="drawer-overlay"></label>
        <ul className="menu p-4 overflow-y-auto w-80 bg-base-100 text-base-content">
          <a href="https://www.bi.go.id">
            <span className={styles.logo}>
              <Image src="/bi-b.png" alt="Bank Indonesia Logo" className='grayscale brightness-200' width={220.1} height={69.7} />
            </span>
          </a>

          <li>
            <Link href="/overview">
              <a>Overview</a>
            </Link>
          </li>
          <li><a>Facebook</a></li>
          <li><a>Instagram</a></li>
          <li><a>Twitter</a></li>
          <li><a>YouTube</a></li>
        </ul>
      </div>

    </div>
  )
}
